""" Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of
the even-valued terms."""


import time

import functools


t0 = time.time()
ans = 0


def is_even(i):  #  bitwise operation to more efficiently test whether x is even
    if i & 1 == 0:
        return True


@functools.lru_cache(128)
def fib_rec(x):
    if x == 0:
        return x
    elif x == 1:
        return x
    return fib_rec(x - 1) + fib_rec(x - 2)


for x in range(34):
    a = fib_rec(x)
    if is_even(a):
        ans += a
print(ans)


t1 = time.time()
print(t1-t0)